/*
	Case Summary
	All Warehouses
*/

SELECT 
	 CAST(CASSAW.ITMTYP	AS INTEGER)"Mfg Whs"
--	,CASSAW.ITMCLS
--	,CASSAW.ITMFML
--	,CASSAW.ITMGRP
--	,CASSAW.MFGLOC
	,CASSAW.PROTYP	"Type of Product"
	,CASSAW.BUYOUT	"Buy Out"
	,CASSAW.WHSE	"Whs"
	,CAST(CASSAW.PROCOD AS INTEGER)	"Item#"
	,CASSAW.PRDESC	"Item Description"
--	,CASSAW.LSTYR
--	,CASSAW.LSTMN
	,CAST(CASSAW.M01QTY AS INTEGER)	"Jan18 Cases"
	,CAST(CASSAW.M02QTY AS INTEGER)	"Fed18 Cases"
	,CAST(CASSAW.M03QTY AS INTEGER)	"Mar18 Cases"
	,CAST(CASSAW.M04QTY AS INTEGER)	"Apr18 Cases"
	,CAST(CASSAW.M05QTY AS INTEGER)	"May18 Cases"
	,CAST(CASSAW.M06QTY AS INTEGER)	"Jun18 Cases"
	,CAST(CASSAW.M07QTY AS INTEGER)	"Jul18 Cases"
	,CAST(CASSAW.M08QTY AS INTEGER)	"Aug17 Cases"
	,CAST(CASSAW.M09QTY AS INTEGER)	"Sep17 Cases"
	,CAST(CASSAW.M10QTY AS INTEGER)	"Oct17 Cases"
	,CAST(CASSAW.M11QTY AS INTEGER)	"Nov17 Cases"
	,CAST(CASSAW.M12QTY AS INTEGER)	"Dec17 Cases"

FROM QS36F.CASSAW CASSAW