SELECT DISTINCT 
	 MBALREP.ALCANB "Customer#"
	,MBALREP.ALCLTX "Customer"
	,MBALREP.ALCMTX "Address"
	,MBALREP.ALCPTX "City"
	,MBALREP.ALBYCD "State"
	,VARCHAR(RIGHT('000000' || MBBFREP.BILNO,6)) "Group"
	,MBBFREP.BFADR6 "Market"
	,RIGHT('00' || MBBFREP.TERRN,2) "Territory"   
FROM AMFLIB.MBALREP MBALREP
JOIN AMFLIB.MBBFREP MBBFREP
   ON MBBFREP.COMNO = MBALREP.ALAENB
  AND MBBFREP.CUSNO = MBALREP.ALCANB
WHERE MBALREP.ALAENB = 01
  AND MBALREP.ALCUCD = 1
  AND MBALREP.ALCANB = 3312501
  AND MBBFREP.BILNO < 999999
  
UNION

SELECT DISTINCT 
	 MBALREP.ALCANB "Customer#"
	,MBALREP.ALCLTX "Customer"
	,MBALREP.ALCMTX "Address"
	,MBALREP.ALCPTX "City"
	,MBALREP.ALBYCD "State"
	,VARCHAR(MBBFREP.BILNO) "Group"
	,MBBFREP.BFADR6 "Market"
	,RIGHT('00' || MBBFREP.TERRN,2) "Territory"   
	,MBBFREP.BILNO
FROM AMFLIB.MBALREP MBALREP
JOIN AMFLIB.MBBFREP MBBFREP 
	ON MBBFREP.COMNO = MBALREP.ALAENB
   AND MBBFREP.CUSNO = MBALREP.ALCANB
WHERE MBALREP.ALAENB =1
  AND MBALREP.ALCUCD = 1 
  AND MBALREP.ALCANB = 3312501
  AND MBBFREP.BILNO > 999999  
  
