/*
 FYTD Leak Freeze Comparison
 Tom Sampson
 08/2/2018
*/

SELECT 

	SALES2YL.SLSMN "Salesname"
	,SALES2YL.REP "Rep"
	,SALES2YL.MKT "Mkt"
	,SALES2YL.TERR "Terr"
	,SALES2YL.CUSNO "Cusno"
	,SALES2YL.CUSNAM "Customer Name"
	,SALES2YL.SHPNM "Ship to Name"
	,SALES2YL.SHPAD1 "Ship to Address 1"
	,SALES2YL.SHPAD2 "Ship to Address 2"
	,SALES2YL.SHPAD3 "Ship to Address 3"
	,SALES2YL.STATE "Ship State"
	,SALES2YL.PROCOD "Item#"
	,SALES2YL.PRODES "Item Description"
--	,SALES2YL.MONTH1 "MONTH1"
--	,SALES2YL.YEAR1 "YEAR1"
--	,SALES2YL.MONTH2 "MONTH2"
--	,SALES2YL.YEAR2 "YEAR2"
	,SALES2YL.AMT1 "FY1718 Gross Sales"
	,SALES2YL.AMT2 "FY1819 Gross Sales"
	,SALES2YL.CASES1 "FY1718 Units"
	,SALES2YL.CASES2 "FY1819 Units"

FROM QS36F.SALES2YL SALES2YL