/*
Goliath Royalty Detail
Tom Sampson 20180802
*/
SELECT 
	 CAST(GOLIATHD.CUSNO AS INTEGER)	"Cusno"
	,GOLIATHD.CUSNM						"Customer Name"
	,CAST(GOLIATHD.INVNO AS INTEGER)	"Invoice Number"
	,GOLIATHD.IDATE						"Invoice Date"
--	,GOLIATHD.YYMMDD
--	,GOLIATHD.ID
	,CAST(GOLIATHD.PROCOD AS INTEGER)	"Item#"
	,GOLIATHD.PRODES					"Item Description"
	,CAST(GOLIATHD.QTYSHP AS INTEGER)	"Units"
	,CAST(GOLIATHD.LINAMT AS DECIMAL(14,2))	"Gross Sales"
	,CAST(GOLIATHD.CASHDL AS DECIMAL(14,2))	"Cash Discount"
	,CAST(GOLIATHD.INVDSC AS DECIMAL(14,2))	"Invoice Discount"
	,CAST(GOLIATHD.DISAMT AS DECIMAL(14,2))	"Rebate Amount"
	,CAST(GOLIATHD.DISRBT AS DECIMAL(14,2))	"Discount & Rebate Total"
	,CAST(GOLIATHD.NETSLS AS DECIMAL(14,2))	"Net Sales"
									
FROM QS36F.GOLIATHD GOLIATHD