/*
 Monthly Profit Summary Prelim
 Tom Sampson
 08/2/2018
*/

SELECT 

--	,PRFRPMID.SLSNO "SLSNO"
--	,PRFRPMID.SLSMNM "SLSMNM"
--	,PRFRPMID.REPNO "REPNO"
--	,PRFRPMID.REPNAM "REPNAM"
--	,PRFRPMID.MKT "MKT"
--	,PRFRPMID.MKTNM "MKTNM"
--	,PRFRPMID.TERR "TERR"
--	,PRFRPMID.GRPNO "GRPNO"
--	,PRFRPMID.GRPNM "GRPNM"
--	,PRFRPMID.CUSNO "CUSNO"
--	,PRFRPMID.CUSNM "CUSNM"
	 PRFRPMID.ITMCLS "Item Class"
	,PRFRPMID.CLSDSC "Item Class Description"
	,PRFRPMID.ITMFML "Item Family"
	,PRFRPMID.FMLDSC "Item Family Description"
	,PRFRPMID.ITMGRP "Item Group"
	,PRFRPMID.GRPDSC "Item Group Description"
--	,PRFRPMID.PROCOD "PROCOD"
--	,PRFRPMID.PRODES "PRODES"
	,PRFRPMID.STRDAT "Start Date"
	,PRFRPMID.ENDDAT "End Date"
--	,PRFRPMID.INVNO "INVNO"
--	,PRFRPMID.ONVDAT "INVDAT"
	,PRFRPMID.UNITS "Units Shipped"
	,PRFRPMID.CASES "Cases Shipped"
	,PRFRPMID.GRSSLS "Gross Sales"
	,PRFRPMID.CASHDS "Cash Discount"
	,PRFRPMID.INVDIS "Invoice Discount"
	,PRFRPMID.OTHDIS "Other Discount"
	,PRFRPMID.NETSLS "Net Sales"
	,PRFRPMID.RM "Raw Materials"
	,PRFRPMID.LO "Labor & Overhead"
	,PRFRPMID.GRSMAR "Gross Margin"
	,CAST((PRFRPMID.GRSMAR/NULLIF(PRFRPMID.NETSLS, 0)) AS DECIMAL(6,3)) "GM %"
	,PRFRPMID.FRT "Freight"
	,PRFRPMID.COMM "Commissions"
	,PRFRPMID.PRTXCN "Pre Tax Contribution"
	,CAST((PRFRPMID.PRTXCP/NULLIF(PRFRPMID.NETSLS, 0)) AS DECIMAL(6,3)) "PTC %"
																			
	
FROM QS36F.PRFRPMID PRFRPMID