/*
	WinWholesale DC Discounts
*/

	
SELECT
--	,WINWDISD.MKTER	"Mkterr"
--	,WINWDISD.CUSNON	"Entity"
	 WINWDISD.DHBYTX	"Name"
	,WINWDISD.BRANCH	"Branch"
	,WINWDISD.SCITY	"City"
	,WINWDISD.DHDXCD	"State"
	,WINWDISD.FECBTX	"PO"
	,WINWDISD.FEGGNB	"Invoice"
	,WINWDISD.IDATE	"Invoice Date"
	,WINWDISD.FEIZVA	"Invoice Amount"
	,WINWDISD.FEAACQ	"Item Amount"
	,WINWDISD.LINAMT01	"Gross Sales"
	,WINWDISD.CASHDL01	"Terms Disc"
--	,WINWDISD.INVDS01	"Invoice Discount"
	,WINWDISD.FRTLIN01	"Freight"
	,WINWDISD.NETSLS	"Net Sales"
	,CAST(WINWDISD.NETSLS*.05 AS DECIMAL(10,2))	"5% DC Discount"


FROM QS36F.WINWDISD WINWDISD