/*
	FYTD Profit Summary Comparison 2
	Tom Sampson
	8/9/2018
*/

SELECT 
  PRFCMYCL.ITMCLS   "Item Class"
, PRFCMYCL.CLSDSC   "Item Class Description"
, PRFCMYCL.ITMFML   "Item Family"
, PRFCMYCL.FMLDSC   "Item Family Description"
-- , PRFCMYCL.ITMGRP   "Item Group"
-- , PRFCMYCL.GRPDSC   "Item Group Description"
-- , PRFCMYCL.PROCOD   "Product Code"
-- , PRFCMYCL.PRODES   "Product Description"
--, PRFCMYCL.TSTRDT   "TY Start Date"
--, PRFCMYCL.TENDDT   "TY End Date"
--, PRFCMYCL.LSTRDT   "LY Start Date"
--, PRFCMYCL.LENDDT   "LY End Date"
, PRFCMYCL.TUNITS   "TY Units Shipped"
, PRFCMYCL.LUNITS   "LY Units Shipped"
, PRFCMYCL.TCASES   "TY Cases Shipped"
, PRFCMYCL.LCASES   "LY Cases Shipped"
, PRFCMYCL.TGRSSL   "TY Gross Sales"
, PRFCMYCL.LGRSSL   "LY Gross Sales"

,(CAST(PRFCMYCL.TGRSSL AS DECIMAL(14,2)) - CAST(PRFCMYCL.LGRSSL AS DECIMAL(14,2)))	"Gross Sales Incr/Decr"

,CAST(CASE WHEN PRFCMYCL.LGRSSL <= 0 THEN 1
			WHEN PRFCMYCL.TGRSSL <= 0 THEN -1
	ELSE (CAST(PRFCMYCL.TGRSSL AS DECIMAL(14,2)) - CAST(PRFCMYCL.LGRSSL AS DECIMAL(14,2)))/CAST(PRFCMYCL.LGRSSL AS DECIMAL(14,2))
 END AS DECIMAL(7,4))	"Gross Sales Incr/  Decr %"



, PRFCMYCL.TCASHD   "TY Cash Discount"
, PRFCMYCL.LCASHD   "LY Cash Discount"
, PRFCMYCL.TINVDS   "TY Invoice Discount"
, PRFCMYCL.LINVDS   "LY Invoice Discount"
, PRFCMYCL.TOTHDS   "TY Other Discount"
, PRFCMYCL.LOTHDS   "LY Other Discount"
, PRFCMYCL.TNETSL   "TY Net Sales"
, PRFCMYCL.LNETSL   "LY Net Sales"
, PRFCMYCL.TRM   "TY Raw Materials"
, PRFCMYCL.LRM   "LY Raw Materials"
, PRFCMYCL.TLO   "TY Labor & Overhead"
, PRFCMYCL.LLO   "LY Labor & Overhead"
, PRFCMYCL.TGRSMR   "TY Gross Margin"
, PRFCMYCL.LGRSMR   "LY Gross Margin"

,(CAST(PRFCMYCL.TGRSMR AS DECIMAL(14,2)) - CAST(PRFCMYCL.LGRSMR AS DECIMAL(14,2)))	"Gross Margin Incr/Decr"

,CAST(CASE WHEN PRFCMYCL.LGRSSL <= 0 THEN 1
			WHEN PRFCMYCL.TGRSMR <= 0 THEN -1
	ELSE (CAST(PRFCMYCL.TGRSMR AS DECIMAL(14,2)) - CAST(PRFCMYCL.LGRSSL AS DECIMAL(14,2)))/CAST(PRFCMYCL.LGRSSL AS DECIMAL(14,2))
 END AS DECIMAL(7,4))	"Gross Margin Incr/Decr %"

,CAST(PRFCMYCL.TGRSMR/PRFCMYCL.TNETSL AS DECIMAL(7,4))	"TY GM %"
,CAST(PRFCMYCL.LGRSMR/PRFCMYCL.LNETSL AS DECIMAL(7,4))	"LY GM %"

--,CAST(PRFCMYCL.TGRSMR AS DECIMAL(14,2)) - CAST(PRFCMYCL.LGRSMR AS DECIMAL(14,2)) AS "GM Incr/Decr"



, PRFCMYCL.TFRT   "TY Freight"
, PRFCMYCL.LFRT   "LY Freight"
, PRFCMYCL.TCOMM   "TY Commissions"
, PRFCMYCL.LCOMM   "LY Commissions"
, PRFCMYCL.TPTXCN   "TY Pre Tax Contribution"
, PRFCMYCL.LPTXCN   "LY Pre Tax Contribution"
, PRFCMYCL.TPTXCN-PRFCMYCL.LPTXCN "Pre Tax Contribution Incr/Decr"

,CAST(PRFCMYCL.TPTXCN/PRFCMYCL.TNETSL AS DECIMAL(7,4))	"TY PTC %"
,CAST(PRFCMYCL.LPTXCN/PRFCMYCL.LNETSL AS DECIMAL(7,4))	"LY PTC %"



	,CAST(CASE WHEN PRFCMYCL.LPTXCN <= 0 THEN 1
			WHEN PRFCMYCL.TPTXCN <= 0 THEN -1
		ELSE (CAST(PRFCMYCL.TPTXCN AS DECIMAL(14,2)) - CAST(PRFCMYCL.LPTXCN AS DECIMAL(14,2)))/CAST(PRFCMYCL.LPTXCN AS DECIMAL(14,2))
		 END AS DECIMAL(7,4)) "PTC Incr/Decr %"


FROM QS36F.PRFCMYCL PRFCMYCL