/*
	Ferguson Volume Descounts
*/

SELECT
--	,FERGDISV.CUSNO5	"Entity"
	 FERGDISV.DHBYTX	"Name"
	,FERGDISV.BRANCH	"Branch"
	,FERGDISV.SCITY	"City"
	,FERGDISV.DHDXCD	"State"
	,FERGDISV.FECBTX	"PO"
	,FERGDISV.FEGGNB	"Invoice"
	,FERGDISV.IDATE	"Invoice Date"
	,FERGDISV.FEIZVA	"Invoice Amount"
	,FERGDISV.FEAACQ	"Item Amount"
	,FERGDISV.LINAMT01	"Gross Sales"
	,FERGDISV.CASHDL01	"Terms Disc"
--	,FERGDISV.INVDS01	"Invoice Discount"
	,FERGDISV.FRTLIN01	"Freight"
	,FERGDISV.NETSLS	"Net Sales"
	,CAST(FERGDISV.NETSLS*.05 AS DECIMAL(10,2))	"5% Volume Rebate"

FROM QS36F.FERGDISV FERGDISV