
SELECT 

	 SALESDUS.MKT	"Mkt"
	,SALESDUS.MKTNM	"Market Name"
	,SALESDUS.TERR	"Terr"
	,SALESDUS.SLSNO	"Slsmno"
	,SALESDUS.SLSMNM	"Salesman Name"
	,SALESDUS.REPNO	"Repno"
	,SALESDUS.REPNAM	"Rep Name"
	,SALESDUS.GRPNO	"Grpno"
	,SALESDUS.GRPNM	"Group Name"
	,SALESDUS.CUSNO	"Cusno"
	,SALESDUS.CUSNM	"Customer Name"
	,SALESDUS.ALCLTX	"Ship to Name"
	,SALESDUS.ALCMTX	"Ship to Address 1"
	,SALESDUS.ALCNTX	"Ship to Address 2"
	,SALESDUS.ALCOTX	"Ship to Address 3"
	,SALESDUS.ALZ9HH	"Ship to Address 4"
	,SALESDUS.ALZ9HG	"Ship to Address 5"
	,SALESDUS.ALCPTX	"City"
	,SALESDUS.ALBYCD	"State"
	,SALESDUS.ALCVCD	"Zip Code"
	,SALESDUS.ALCOCD	"Country Code"
	,SALESDUS.BBCJTX	"Country"
	,SALESDUS.SHPTEL	"Phone Number"
	,SALESDUS.COMCOD	"Item Class"
	,SALESDUS.COMCNM	"Item Class Description"
	,SALESDUS.VIP	"Item Family"
	,SALESDUS.VIPNM	"Item Family Description"
	,SALESDUS.ID	"Item Group"
	,SALESDUS.IDNM	"Item Group Description"
	,SALESDUS.PROCOD	"Item#"
	,SALESDUS.PRODES	"Item Description"
	,SALESDUS.YEAR	"Fiscal Year"
	,SALESDUS.QUARTR	"Quarter"
	,SALESDUS.MONTH	"Month"
	,SALESDUS.CASES	"Cases"
	,SALESDUS.UNITS	"Units"
	,SALESDUS.AMOUNT	"Amount"
	,SALESDUS.PRICE	"Commissions"


FROM QS36F.SALESDUS SALESDUS