/*
 FYTD Profit Summary Comparison
 Tom Sampson
 8/9/2018
*/

SELECT 

	 PRFCMYID.ITMCLS	"Item Class"
	,PRFCMYID.CLSDSC	"Item Class Description"
	,PRFCMYID.ITMFML	"Item Family"
	,PRFCMYID.FMLDSC	"Item Family Description"
	,PRFCMYID.ITMGRP	"Item Group"
	,PRFCMYID.GRPDSC	"Item Group Description"
	,PRFCMYID.PROCOD	"PROCOD"
	,PRFCMYID.PRODES	"PRODES"
	,PRFCMYID.TSTRDT	"TY Start Date"
	,PRFCMYID.TENDDT	"TY End Date"
	,PRFCMYID.LSTRDT	"LY Start Date"
	,PRFCMYID.LENDDT	"LY End Date"
	,PRFCMYID.TUNITS	"TY Units Shipped"
	,PRFCMYID.LUNITS	"LY Units Shipped"
	,PRFCMYID.TCASES	"TY Cases Shipped"
	,PRFCMYID.LCASES	"LY Cases Shipped"
	,PRFCMYID.TGRSSL	"TY Gross Sales"
	,PRFCMYID.LGRSSL	"LY Gross Sales"
	,(CAST(PRFCMYID.TGRSSL AS DECIMAL(14,2)) - CAST(PRFCMYID.LGRSSL AS DECIMAL(14,2)))	"Gross Sales Incr/Decr"
	
	,CAST(CASE WHEN PRFCMYID.LGRSSL <= 0 THEN 1
				WHEN PRFCMYID.TGRSSL <= 0 THEN -1
		ELSE (CAST(PRFCMYID.TGRSSL AS DECIMAL(14,2)) - CAST(PRFCMYID.LGRSSL AS DECIMAL(14,2)))/CAST(PRFCMYID.LGRSSL AS DECIMAL(14,2))
	 END AS DECIMAL(7,4))	"Gross Sales Incr/  Decr %"
	,PRFCMYID.TCASHD	"TY Cash Discount"
	,PRFCMYID.LCASHD	"LY Cash Discount"
	,PRFCMYID.TINVDS	"TY Invoice Discount"
	,PRFCMYID.LINVDS	"LY Invoice Discount"
	,PRFCMYID.TOTHDS	"TY Other Discount"
	,PRFCMYID.LOTHDS	"LY Other Discount"
	,PRFCMYID.TNETSL	"TY Net Sales"
	,PRFCMYID.LNETSL	"LY Net Sales"
	,PRFCMYID.TRM	"TY Raw Materials"
	,PRFCMYID.LRM	"LY Raw Materials"
	,PRFCMYID.TLO	"TY Labor & Overhead"
	,PRFCMYID.LLO	"LY Labor & Overhead"
	,PRFCMYID.TGRSMR	"TY Gross Margin"
	,PRFCMYID.LGRSMR	"LY Gross Margin"
	,(CAST(PRFCMYID.TGRSMR AS DECIMAL(14,2)) - CAST(PRFCMYID.LGRSMR AS DECIMAL(14,2)))	"Gross Margin Incr/Decr "
	,CAST((CAST(PRFCMYID.TGRSMR AS DECIMAL(14,2))/CAST(PRFCMYID.TNETSL AS DECIMAL(14,2))) AS DECIMAL(7,4))	"TY     GM %"
	,CAST((CAST(PRFCMYID.LGRSMR AS DECIMAL(14,2))/CAST(PRFCMYID.LNETSL AS DECIMAL(14,2))) AS DECIMAL(7,4))	"LY     GM %"
	
	,CAST(CASE WHEN PRFCMYID.LGRMRP <= 0 THEN 1
				WHEN PRFCMYID.TGRMRP <= 0 THEN -1
		ELSE (CAST(PRFCMYID.TGRMRP AS DECIMAL(14,2)) - CAST(PRFCMYID.LGRMRP AS DECIMAL(14,2)))/CAST(PRFCMYID.LGRMRP AS DECIMAL(14,2))
	 END AS DECIMAL(7,4))	"GM Incr/  Decr %"
	,PRFCMYID.TFRT	"TY Freight"
	,PRFCMYID.LFRT	"LY Freight"
	,PRFCMYID.TCOMM	"TY Commissions"
	,PRFCMYID.LCOMM	"LY Commissions"
	,PRFCMYID.TPTXCN	"TY Pre Tax Contribution"
	,PRFCMYID.LPTXCN	"LY Pre Tax Contribution"
	
	,(CAST(PRFCMYID.TPTXCN AS DECIMAL(14,2)) - CAST(PRFCMYID.LCOMM AS DECIMAL(14,2)))	"Pre Tax Contribution Incr/Decr"

	,CAST(PRFCMYID.TPTXCN/PRFCMYID.TNETSL AS DECIMAL(7,4))	"TY     PTC %"
	
	,CAST(PRFCMYID.LPTXCN/PRFCMYID.LNETSL AS DECIMAL(7,4))	"LY     PTC %"
	
	,CAST(CASE WHEN PRFCMYID.LPTXCN <= 0 THEN 1
			WHEN PRFCMYID.TPTXCN <= 0 THEN -1
		ELSE (CAST(PRFCMYID.TPTXCN AS DECIMAL(14,2)) - CAST(PRFCMYID.LCOMM AS DECIMAL(14,2)))/CAST(PRFCMYID.LPTXCN AS DECIMAL(14,2))
		 END AS DECIMAL(7,4)) "PTC   Incr/  Decr %"


FROM QS36F.PRFCMYID PRFCMYID