/*
	FYTD Private Label Profit Summary
	Tom Sampson
	8/8/2018
*/

SELECT 

--	 PRFRPYPL.SLSNO	"SLSNO"
--	,PRFRPYPL.SLSMNM	"SLSMNM"
--	,PRFRPYPL.REPNO	"REPNO"
--	,PRFRPYPL.REPNAM	"REPNAM"
	 PRFRPYPL.MKT	"PvtLbl Code "
	,PRFRPYPL.MKTNM	"Private Label Customer"
--	,PRFRPYPL.TERR	"TERR"
--	,PRFRPYPL.GRPNO	"GRPNO"
--	,PRFRPYPL.GRPNM	"GRPNM"
--	,PRFRPYPL.CUSNO	"CUSNO"
--	,PRFRPYPL.CUSNM	"CUSNM"
	,PRFRPYPL.ITMCLS	"Item Class"
	,PRFRPYPL.CLSDSC	"Item Class Description"
	,PRFRPYPL.ITMFML	"Item Family"
	,PRFRPYPL.FMLDSC	"Item Family Description"
	,PRFRPYPL.ITMGRP	"Item Group"
	,PRFRPYPL.GRPDSC	"Item Group Description"
--	,PRFRPYPL.PROCOD	"PROCOD"
--	,PRFRPYPL.PRODES	"PRODES"
	,PRFRPYPL.STRDAT	"Start Date"
	,PRFRPYPL.ENDDAT	"End Date"
--	,PRFRPYPL.INVNO	"INVNO"
--	,PRFRPYPL.INVDAT	"INVDAT"
	,PRFRPYPL.UNITS	"Units Shipped"
	,PRFRPYPL.CASES	"Cases Shipped"
	,PRFRPYPL.GRSSLS	"Gross Sales"
	,PRFRPYPL.CASHDS	"Cash Discount"
	,PRFRPYPL.INVDIS	"Invoice Discount"
	,PRFRPYPL.OTHDIS	"Other Discount"
	,PRFRPYPL.NETSLS	"Net Sales"
	,PRFRPYPL.RM	"Raw Materials"
	,PRFRPYPL.LO	"Labor & Overhead"
	,PRFRPYPL.GRSMAR	"Gross Margin"
	,CAST(PRFRPYPL.GRSMRP/100 AS DECIMAL(10,2))	"GM %"
	,PRFRPYPL.FRT	"Freight"
	,PRFRPYPL.COMM	"Commissions"
	,PRFRPYPL.PRTXCN	"Pre Tax Contribution"
	,CAST(PRFRPYPL.PRTXCN/PRFRPYPL.NETSLS AS DECIMAL(10,2))	"PTC %"


FROM QS36F.PRFRPYPL PRFRPYPL