/*
    Use this with MS Excel to lookup table info
    Tom Sampson
    20180829
*/
SELECT 
	 SYSCOLUMNS.TABLE_SCHEMA "Schema"
	,SYSCOLUMNS.TABLE_NAME "Table"
	,SYSCOLUMNS.COLUMN_NAME "Column Name"
	,SYSCOLUMNS.COLUMN_TEXT "Column Text"
	,SYSCOLUMNS.DATA_TYPE "Data Type"
	,SYSCOLUMNS.LENGTH "length"
	,SYSCOLUMNS.NUMERIC_SCALE "Numeric Scale"
	,SYSCOLUMNS.NUMERIC_PRECISION "Numeric Precision"
	,SYSCOLUMNS.IS_NULLABLE "Is Nullable?"
	
FROM QSYS2.SYSCOLUMNS SYSCOLUMNS

WHERE 
	SYSCOLUMNS.TABLE_SCHEMA = ?
AND SYSCOLUMNS.TABLE_NAME = ?